### ISSUE TITLE
Confusion about the wavelink cable

### ISSUE THREAD

**Issue by twiclo** [IBM-1620/Cadetwriter#8]
Can you please be more specific about the type of cable needed from wavelink? Digikey has many flex cables so if it's possible I'd like to see if I can get it from digikey

**Comment by slcasner** [comment]
On Tue, 22 Feb 2022, Tanner Wilcox wrote:

> Can you please be more specific about the type of cable needed from
> wavelink? Digikey has many flex cables so if it's possible I'd like
> to see if I can get it from digikey

The part numbers for the Wavelink cables are shown in the Parts List
of the wheelwriter-adaptation-instructions.pdf guide: 254-015-0155-AA
and 254-015-0155-AB, with same side and opposite side contacts,
respectively.  These are flat flex cables with no connectors on the
ends, they just have the plastic covering cut away to expose the
traces that are then plated.  These cables fit nicely into the
existing connectors on the Wheelwriter logic board.

The Digikey cables have a latching plastic connector on the end.  We
used those for our first prototype, but that required removing (and
harvesting) the connectors from the Wheelwriter logic board to move
them to the serial interface board.  That is not easy and risks damage
to the logic board.

Our updated design uses the Wavelink cables together with the same
type of ZIF connectors that are on the logic board.  This was enabled
after we finally found a source for those connectors -- Heilind.  But
I bought 50 of them just in case they stopped being available.  I can
send four of them to you for $1 each plus USPS shipping if you like.

                                                        -- Steve

**Comment by twiclo** [comment]
I appreciate the offer but maybe we can find a product on digikey so future visitors won't have to rely on an out of production cable. I'm wondering why I can't buy the cable off digikey and remove the connector myself.  Or maybe I can buy something like this?
https://www.digikey.com/en/products/detail/samtec-inc/FJH-40-D-24-00-4/6023772

**Comment by slcasner** [comment]
Are you saying that Wavelink no longer has any stock?  They agreed to make 25 sets for me on speculation, and I have been concerned that there would not be enough takers.

**Comment by twiclo** [comment]
I haven't contacted WaveLink yet. I'll go through them or you to get the cable. I'm only asking what the difference is between these wavelink cables and the one I posted. Wouldn't it be better if these cables could be included in the order everyone who does this has to make on digikey?

**Comment by slcasner** [comment]
The specific cable you referenced is not wide enough and is so long it would get in the way.  I did test some 80-conductor 0.5mm pitch 150mm length FFC cables that I found on ebay, figuring that at least one of the conductors would contact the pin in the connector.  I was able to get them to work in the Wheelwriter 1000 but they are not as thick/firm so it was harder to push them into the connectors.
 but not in the Wheelwriter Model 30 Series II because that logic board uses a true ZIF connector (zero rather than just low insertion force) with a latch where the metal of the pin is perpendicular to the cable surface and therefore touches only a narrow edge.  But you would still need the connectors from Heilind, so the order would not all come from Digikey.
You also asked about buying the Digikey cables with latching connectors and removing the connectors on the ends mating with the logic board.  Chopping off the connector and then peeling back the plastic cover would be difficult to do without damaging the copper conductors, and then the unplated copper would tend to oxidize over time (the Wavelink cables have gold platiing).  You would also need to attach a stiffener to the back side.
I strongly suggest that your best course of action would be to buy the cables from Wavelink.

**Comment by twiclo** [comment]
Fair enough. I'll contact them and follow up if they're unable to provide me with the cable

**Comment by twiclo** [comment]
Actually can I take you up on your offer? They want $25 per cable

**Comment by slcasner** [comment]
Hmm, that is a jump from the $15 they quoted before, but I think still not unreasonable.  When we were trying to find a source for cables to fit the logic board, the other vendors who could make them wanted $1000 setup cost for a run since this dimensions of these cables are outdated.

My offer was for the FFC connectors (TE/AMP 6-520315-5) that you otherwise need to get from Heilind since I bought 50 of them.  I don't have the FFC cables to sell.

**Comment by twiclo** [comment]
I'm finally getting around to ordering parts for the conversion and would like to take you up on the offer for those connectors. Can you please shoot me an email so we can coordinate: tanner@twil.cx

**Comment by slcasner** [comment]
Email sent.
